### ISSUE TITLE
Exercise correction 6,7,9,10

### ISSUE THREAD

**Issue by Rajasi-Desai** [umass-cs-326/umass-cs-326.github.io#52]
In all exercises just a small fix:

- Remove the headings: "Submissions" and "Rubric and Grading"
- In the starter kit, instead of "Download the starter kit" put a note to download it from GitHub classroom (i.e remove the link completely)

:::note

Follow the GitHub Classroom assignment link on Moodle first.

:::

**Comment by RobotGeissler** [comment]
Fixed

**Comment by Rajasi-Desai** [comment]
Okay, this was my bad in communication.

But can you remove the content related to  "Submissions" and "Rubric and Grading" as well?

**Comment by RobotGeissler** [comment]
I see, will do
